name: Pedro Zappa
favicon: null
layout_spectrum: 0.1586
typography_spectrum: 0.79633
title: "Z's Grey Matter Bonanza "
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72869816-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cba98d'
    - '#996a49'
    - '#604834'
    - '#fff8ff'
  brandStrength: 0.125
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
