name: Pedro Zappa
favicon: null
layout_spectrum: 0.66776
typography_spectrum: 0.79419
title: Pedro Zappa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cba98d'
    - '#996a49'
    - '#604834'
    - '#fff8ff'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
