name: Pedro Zappa
favicon: null
layout_spectrum: 0.33387
typography_spectrum: 0.7825043441262096
title: Pedro Zappa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120111'
    - '#0926b3'
    - '#8d4ac8'
    - '#b182be'
    - '#ebd8f2'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.7317281202413142
purpose: []
